import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { OpenCarapaceConfig } from "./types";
import { expandHomePath } from "./path";

const DEFAULT_CONFIG_RELATIVE = ".config/opencarapace/config.toml";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isTomlScalar(value: unknown): value is string | number | boolean {
  return typeof value === "string" || typeof value === "number" || typeof value === "boolean";
}

function isTomlArray(value: unknown): value is Array<string | number | boolean> {
  return Array.isArray(value) && value.every((entry) => isTomlScalar(entry));
}

function toTomlValue(value: string | number | boolean | Array<string | number | boolean>): string {
  if (Array.isArray(value)) {
    return `[${value.map((entry) => toTomlValue(entry)).join(", ")}]`;
  }
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  return String(value);
}

function emitTable(lines: string[], tablePath: string[], value: Record<string, unknown>): void {
  const scalarEntries: Array<{ key: string; value: string | number | boolean | Array<string | number | boolean> }> = [];
  const objectEntries: Array<{ key: string; value: Record<string, unknown> }> = [];

  const keys = Object.keys(value).sort((left, right) => left.localeCompare(right));
  for (const key of keys) {
    const entry = value[key];
    if (entry === undefined || entry === null) {
      continue;
    }
    if (isTomlScalar(entry) || isTomlArray(entry)) {
      scalarEntries.push({ key, value: entry });
      continue;
    }
    if (isRecord(entry)) {
      objectEntries.push({ key, value: entry });
    }
  }

  if (tablePath.length > 0 && (scalarEntries.length > 0 || objectEntries.length > 0)) {
    lines.push(`[${tablePath.join(".")}]`);
  }
  for (const entry of scalarEntries) {
    lines.push(`${entry.key} = ${toTomlValue(entry.value)}`);
  }
  if (tablePath.length > 0 && (scalarEntries.length > 0 || objectEntries.length > 0)) {
    lines.push("");
  }

  for (const entry of objectEntries) {
    emitTable(lines, [...tablePath, entry.key], entry.value);
  }
}

function safeParseToml(input: string): unknown {
  if (typeof Bun === "undefined" || !Bun.TOML) {
    throw new Error("TOML parsing requires Bun runtime.");
  }
  return Bun.TOML.parse(input);
}

export function resolveOpenCarapaceConfigPath(explicitPath?: string): string {
  const override = explicitPath?.trim();
  if (override) {
    return path.resolve(expandHomePath(override));
  }
  return path.resolve(os.homedir(), DEFAULT_CONFIG_RELATIVE);
}

export function defaultOpenCarapaceConfig(): OpenCarapaceConfig {
  return {
    runtime: {
      default_agent_id: "codex",
      session_store_file: "sessions.json",
      project_root_dir: path.resolve(os.homedir(), "Documents"),
      port: 3000,
      gateway_port: 3010,
      language: "en",
    },
    agents: {
      codex: {
        enabled: true,
        cli_command: "codex",
        cli_args: ["exec", "{{prompt}}"],
      },
      claude_code: {
        enabled: false,
      },
    },
    channels: {
      routing: {
        default_agent_id: "codex",
      },
      telegram: {
        enabled: false,
      },
      slack: {
        enabled: false,
      },
      discord: {
        enabled: false,
      },
    },
    skills: {
      enable_openclaw_catalog: true,
    },
  };
}

export function renderOpenCarapaceConfigToml(config: OpenCarapaceConfig): string {
  const lines: string[] = [
    "# OpenCarapace configuration",
    "# Generated by `opencarapace config init|tui|set`",
    "",
  ];
  emitTable(lines, [], config as Record<string, unknown>);
  while (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }
  lines.push("");
  return lines.join("\n");
}

export function loadOpenCarapaceConfig(params?: {
  path?: string;
  strict?: boolean;
}): OpenCarapaceConfig {
  const filePath = resolveOpenCarapaceConfigPath(params?.path);
  if (!fs.existsSync(filePath)) {
    return {};
  }
  const raw = fs.readFileSync(filePath, "utf-8");
  if (!raw.trim()) {
    return {};
  }
  try {
    const parsed = safeParseToml(raw);
    if (!isRecord(parsed)) {
      return {};
    }
    return parsed as OpenCarapaceConfig;
  } catch (error) {
    if (params?.strict === false) {
      return {};
    }
    throw new Error(
      `failed to parse config at ${filePath}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

export function saveOpenCarapaceConfig(config: OpenCarapaceConfig, params?: { path?: string }): string {
  const filePath = resolveOpenCarapaceConfigPath(params?.path);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, renderOpenCarapaceConfigToml(config), "utf-8");
  return filePath;
}

export function ensureOpenCarapaceConfig(params?: { path?: string }): {
  filePath: string;
  created: boolean;
  config: OpenCarapaceConfig;
} {
  const filePath = resolveOpenCarapaceConfigPath(params?.path);
  if (fs.existsSync(filePath)) {
    return {
      filePath,
      created: false,
      config: loadOpenCarapaceConfig({ path: filePath }),
    };
  }
  const config = defaultOpenCarapaceConfig();
  saveOpenCarapaceConfig(config, { path: filePath });
  return {
    filePath,
    created: true,
    config,
  };
}

export function setConfigValueByPath(
  config: OpenCarapaceConfig,
  keyPath: string,
  value: unknown,
): OpenCarapaceConfig {
  const keys = keyPath
    .split(".")
    .map((item) => item.trim())
    .filter(Boolean);
  if (keys.length === 0) {
    throw new Error("config key path is empty");
  }

  let cursor: Record<string, unknown> = config as Record<string, unknown>;
  for (let i = 0; i < keys.length - 1; i += 1) {
    const key = keys[i];
    if (!key) {
      continue;
    }
    const current = cursor[key];
    if (!isRecord(current)) {
      cursor[key] = {};
    }
    cursor = cursor[key] as Record<string, unknown>;
  }
  const leaf = keys[keys.length - 1];
  if (!leaf) {
    throw new Error("config key path is empty");
  }
  cursor[leaf] = value;
  return config;
}

export function parseConfigValue(raw: string): unknown {
  const value = raw.trim();
  if (!value) {
    return "";
  }
  if (value === "true") {
    return true;
  }
  if (value === "false") {
    return false;
  }
  if (value === "null") {
    return "";
  }
  if (/^-?\d+(\.\d+)?$/.test(value)) {
    return Number(value);
  }
  if (value.startsWith("[") && value.endsWith("]")) {
    try {
      const parsed = JSON.parse(value);
      if (Array.isArray(parsed)) {
        return parsed.map((entry) => String(entry));
      }
    } catch {
      // ignore json parse failure and fallback to string
    }
  }
  if (value.includes(",") && !value.includes(" ")) {
    return value
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  }
  return value;
}
